{{- range $component := list "frontend" "backend" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todoapp.fullname" $ }}-{{ $component }}
  labels:
    {{- include "todoapp.labels" $ | nindent 4 }}
    component: {{ $component }}
spec:
  replicas: {{ index $.Values $component "replicaCount" }}
  selector:
    matchLabels:
      {{- include "todoapp.selectorLabels" $ | nindent 6 }}
      component: {{ $component }}
  template:
    metadata:
      labels:
        {{- include "todoapp.selectorLabels" $ | nindent 8 }}
        component: {{ $component }}
    spec:
      {{- if $.Values.postgresql.enabled}}
      initContainers:
        - name: wait-for-postgres
          image: busybox:latest
          command: ['sh', '-c', 'until nc -z {{ include "todoapp.fullname" $ }}-postgresql 5432; do echo "Waiting for postgres..."; sleep 3; done;']
      {{- end }}
      containers:
        - name: {{ $component }}
          image: "{{ index $.Values $component "image" "repository" }}:{{ index $.Values $component "image" "tag" }}"
          imagePullPolicy: {{ index $.Values $component "image" "pullPolicy" }}
          ports:
            - name: http
              containerPort: {{ index $.Values $component "service" "targetPort" }}
              protocol: TCP
          {{- if and (eq $component "backend") (or $.Values.postgresql.enabled $.Values.postgresql.external.enabled) }}
          env:
            - name: DATABASE_URL
              value: "{{ if $.Values.postgresql.enabled }}postgresql://{{ $.Values.postgresql.auth.username }}:{{ $.Values.postgresql.auth.password }}@{{ include "todoapp.fullname" $ }}-postgresql:5432/{{ $.Values.postgresql.auth.database }}{{ else }}postgresql://{{ $.Values.postgresql.external.username }}:{{ $.Values.postgresql.external.password }}@{{ $.Values.postgresql.external.host }}:{{ $.Values.postgresql.external.port }}/{{ $.Values.postgresql.external.database }}{{ end }}"
          {{- end }}
          resources:
            {{- index $.Values $component "resources" | toYaml | nindent 12 }}
---
{{- end }}